# Generated by Django 5.2 on 2026-03-19 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='markets.sector')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='markets.industry')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='markets.sector')),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='PrecomputedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('1min', '1 Minute'), ('5min', '5 Minutes'), ('15min', '15 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], max_length=10)),
                ('as_of_date', models.DateField(db_index=True)),
                ('change_1d', models.FloatField(blank=True, null=True)),
                ('change_1w', models.FloatField(blank=True, null=True)),
                ('change_2w', models.FloatField(blank=True, null=True)),
                ('change_1m', models.FloatField(blank=True, null=True)),
                ('change_3m', models.FloatField(blank=True, null=True)),
                ('change_6m', models.FloatField(blank=True, null=True)),
                ('change_1y', models.FloatField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='markets.symbol')),
            ],
            options={
                'ordering': ['-as_of_date', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='OHLCVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('1min', '1 Minute'), ('5min', '5 Minutes'), ('15min', '15 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], db_index=True, max_length=10)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('data', models.JSONField()),
                ('first_date', models.DateField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv_data', to='markets.symbol')),
            ],
            options={
                'ordering': ['symbol', 'frequency', 'year'],
            },
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['ticker', 'is_active'], name='markets_sym_ticker_9cd341_idx'),
        ),
        migrations.AddIndex(
            model_name='precomputedmetrics',
            index=models.Index(fields=['symbol', 'frequency', '-as_of_date'], name='markets_pre_symbol__a96126_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='precomputedmetrics',
            unique_together={('symbol', 'frequency', 'as_of_date')},
        ),
        migrations.AddIndex(
            model_name='ohlcvdata',
            index=models.Index(fields=['symbol', 'frequency', 'year'], name='markets_ohl_symbol__135c87_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcvdata',
            index=models.Index(fields=['frequency', 'year'], name='markets_ohl_frequen_a19c0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ohlcvdata',
            unique_together={('symbol', 'frequency', 'year')},
        ),
    ]
