# Generated by Django 5.2 on 2026-03-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dashboard Configuration',
                'verbose_name_plural': 'Dashboard Configurations',
            },
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_drawdown_duration',
            field=models.IntegerField(blank=True, help_text='Longest drawdown duration in days over next year', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_drawdown',
            field=models.FloatField(blank=True, help_text='Maximum drawdown over next year', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_1d',
            field=models.FloatField(blank=True, help_text='Maximum % drop in next 1 day', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_1m',
            field=models.FloatField(blank=True, help_text='Maximum % drop in next 1 month', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_1w',
            field=models.FloatField(blank=True, help_text='Maximum % drop in next 1 week', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_1y',
            field=models.FloatField(blank=True, help_text='Maximum % drop in next 1 year', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_2w',
            field=models.FloatField(blank=True, help_text='Maximum % drop in next 2 weeks', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_3m',
            field=models.FloatField(blank=True, help_text='Maximum % drop in next 3 months', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_6m',
            field=models.FloatField(blank=True, help_text='Maximum % drop in next 6 months', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_1d',
            field=models.FloatField(blank=True, help_text='Maximum % rise in next 1 day', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_1m',
            field=models.FloatField(blank=True, help_text='Maximum % rise in next 1 month', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_1w',
            field=models.FloatField(blank=True, help_text='Maximum % rise in next 1 week', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_1y',
            field=models.FloatField(blank=True, help_text='Maximum % rise in next 1 year', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_2w',
            field=models.FloatField(blank=True, help_text='Maximum % rise in next 2 weeks', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_3m',
            field=models.FloatField(blank=True, help_text='Maximum % rise in next 3 months', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_6m',
            field=models.FloatField(blank=True, help_text='Maximum % rise in next 6 months', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_sharpe_ratio',
            field=models.FloatField(blank=True, help_text='Sharpe ratio over next year (assuming risk-free rate of 2%)', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_volatility_1m',
            field=models.FloatField(blank=True, help_text='Volatility (std dev of returns) over next 1 month', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_volatility_3m',
            field=models.FloatField(blank=True, help_text='Volatility over next 3 months', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_volatility_6m',
            field=models.FloatField(blank=True, help_text='Volatility over next 6 months', null=True),
        ),
    ]
