# Generated by Django 5.2 on 2026-03-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_dashboardconfig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_1d',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_1m',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_1w',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_1y',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_2w',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_3m',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_drop_6m',
        ),
    ]
