# Generated by Django 5.2 on 2026-03-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_remove_fwd_drop_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_1d',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_1m',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_1w',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_1y',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_2w',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_3m',
        ),
        migrations.RemoveField(
            model_name='precomputedmetrics',
            name='fwd_max_rise_6m',
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_change_1d',
            field=models.FloatField(blank=True, help_text='% fwd chg in next 1 day', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_change_1m',
            field=models.FloatField(blank=True, help_text='% fwd chg in next 1 month', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_change_1w',
            field=models.FloatField(blank=True, help_text='% fwd chg in next 1 week', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_change_1y',
            field=models.FloatField(blank=True, help_text='% fwd chg in next 1 year', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_change_2w',
            field=models.FloatField(blank=True, help_text='% fwd chg in next 2 weeks', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_change_3m',
            field=models.FloatField(blank=True, help_text='% fwd chg in next 3 months', null=True),
        ),
        migrations.AddField(
            model_name='precomputedmetrics',
            name='fwd_change_6m',
            field=models.FloatField(blank=True, help_text='% fwd chg in next 6 months', null=True),
        ),
    ]
