# Generated by Django 5.2 on 2026-03-22 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_rename_forward_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('1min', '1 Minute'), ('5min', '5 Minutes'), ('15min', '15 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], max_length=10)),
                ('as_of_date', models.DateField(db_index=True)),
                ('sma_9', models.FloatField(blank=True, null=True)),
                ('sma_20', models.FloatField(blank=True, null=True)),
                ('sma_30', models.FloatField(blank=True, null=True)),
                ('sma_50', models.FloatField(blank=True, null=True)),
                ('sma_100', models.FloatField(blank=True, null=True)),
                ('sma_200', models.FloatField(blank=True, null=True)),
                ('ema_9', models.FloatField(blank=True, null=True)),
                ('ema_20', models.FloatField(blank=True, null=True)),
                ('ema_30', models.FloatField(blank=True, null=True)),
                ('ema_50', models.FloatField(blank=True, null=True)),
                ('ema_100', models.FloatField(blank=True, null=True)),
                ('ema_200', models.FloatField(blank=True, null=True)),
                ('rsi_14', models.FloatField(blank=True, null=True)),
                ('stoch_k_fast', models.FloatField(blank=True, null=True)),
                ('stoch_d_fast', models.FloatField(blank=True, null=True)),
                ('stoch_k_slow', models.FloatField(blank=True, null=True)),
                ('stoch_d_slow', models.FloatField(blank=True, null=True)),
                ('atr_14', models.FloatField(blank=True, null=True)),
                ('beta_252', models.FloatField(blank=True, help_text='Beta vs S&P 500 (252 days)', null=True)),
                ('high_1w', models.FloatField(blank=True, null=True)),
                ('low_1w', models.FloatField(blank=True, null=True)),
                ('high_1m', models.FloatField(blank=True, null=True)),
                ('low_1m', models.FloatField(blank=True, null=True)),
                ('high_3m', models.FloatField(blank=True, null=True)),
                ('low_3m', models.FloatField(blank=True, null=True)),
                ('high_1y', models.FloatField(blank=True, null=True)),
                ('low_1y', models.FloatField(blank=True, null=True)),
                ('perf_week', models.FloatField(blank=True, null=True)),
                ('perf_month', models.FloatField(blank=True, null=True)),
                ('perf_quarter', models.FloatField(blank=True, null=True)),
                ('perf_half_y', models.FloatField(blank=True, null=True)),
                ('perf_ytd', models.FloatField(blank=True, null=True)),
                ('perf_year', models.FloatField(blank=True, null=True)),
                ('avg_volume_20d', models.FloatField(blank=True, null=True)),
                ('avg_volume_50d', models.FloatField(blank=True, null=True)),
                ('relative_volume', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('change_open', models.FloatField(blank=True, help_text='% change from open', null=True)),
                ('gap', models.FloatField(blank=True, help_text='% gap from previous close', null=True)),
                ('range_52w', models.FloatField(blank=True, help_text='% of 52-week range', null=True)),
                ('vwap_week', models.FloatField(blank=True, null=True)),
                ('poc_week', models.FloatField(blank=True, null=True)),
                ('vwap_month', models.FloatField(blank=True, null=True)),
                ('poc_month', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_indicators', to='markets.symbol')),
            ],
            options={
                'ordering': ['-as_of_date', 'symbol'],
                'indexes': [models.Index(fields=['symbol', 'frequency', '-as_of_date'], name='markets_tec_symbol__f584d5_idx'), models.Index(fields=['rsi_14'], name='markets_tec_rsi_14_7a16ad_idx'), models.Index(fields=['sma_50', 'sma_200'], name='markets_tec_sma_50_4e49d4_idx'), models.Index(fields=['relative_volume'], name='markets_tec_relativ_8cdebb_idx')],
                'unique_together': {('symbol', 'frequency', 'as_of_date')},
            },
        ),
    ]
