# Generated by Django 5.2 on 2026-03-22 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_technicalindicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalindicators',
            name='precomputed_metrics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='technical_indicators', to='markets.precomputedmetrics'),
            preserve_default=False,
        ),
    ]
