# Generated by Django 5.2 on 2026-03-28 04:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0006_technicalindicators_precomputed_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('fast_sma', models.IntegerField(default=100, help_text='Fast SMA for trend identification')),
                ('slow_sma', models.IntegerField(default=200, help_text='Slow SMA for trend identification')),
                ('pullback_ema_fast', models.IntegerField(default=50, help_text='Fast EMA for pullback zone')),
                ('pullback_ema_slow', models.IntegerField(default=100, help_text='Slow EMA for pullback zone')),
                ('stochastic_period', models.IntegerField(default=14)),
                ('stochastic_overbought', models.IntegerField(default=75)),
                ('stochastic_oversold', models.IntegerField(default=25)),
                ('vwap_anchor', models.CharField(choices=[('session', 'Session'), ('week', 'Week'), ('month', 'Month')], default='session', max_length=20)),
                ('regression_period', models.IntegerField(default=20)),
                ('regression_threshold', models.FloatField(default=0.001)),
                ('risk_reward_ratios', models.JSONField(default=list, help_text='List of risk:reward ratios to test')),
                ('default_stop_loss', models.FloatField(default=0.02, help_text='Default stop loss percentage')),
                ('use_ema_pullback', models.BooleanField(default=True)),
                ('use_stochastic', models.BooleanField(default=True)),
                ('use_vwap_deviation', models.BooleanField(default=True)),
                ('use_regression_trend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLTrendDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict, help_text='Features and labels')),
                ('frequency', models.CharField(choices=[('1min', '1 Minute'), ('5min', '5 Minutes'), ('15min', '15 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_samples', models.IntegerField(default=0)),
                ('feature_names', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_trend_datasets', to='markets.symbol')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='ml_trend.trendconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLTrendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('algorithm', models.CharField(choices=[('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('random_forest', 'Random Forest')], max_length=50)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('target_rr_ratio', models.FloatField(help_text='Risk:Reward ratio used for labeling')),
                ('target_lookahead', models.IntegerField(help_text='Lookahead periods for take profit')),
                ('training_date', models.DateField(auto_now_add=True)),
                ('training_samples', models.IntegerField()),
                ('performance_metrics', models.JSONField(default=dict)),
                ('feature_importance', models.JSONField(default=dict)),
                ('model_file_path', models.CharField(blank=True, max_length=500)),
                ('scaler_file_path', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ml_trend.mltrenddataset')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ml_trend.trendconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='TrendSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('signal_type', models.CharField(choices=[('LONG', 'Long Entry'), ('SHORT', 'Short Entry'), ('EXIT', 'Exit')], max_length=10)),
                ('trend_direction', models.CharField(choices=[('UPTREND', 'Uptrend'), ('DOWNTREND', 'Downtrend'), ('SIDEWAYS', 'Sideways')], max_length=10)),
                ('entry_price', models.FloatField()),
                ('entry_confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=50)),
                ('actual_return', models.FloatField(blank=True, null=True)),
                ('achieved_rr_ratio', models.FloatField(blank=True, null=True)),
                ('indicators_at_entry', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='ml_trend.trendconfig')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_signals', to='markets.symbol')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='ml_trend_tr_symbol__cb0e3b_idx'), models.Index(fields=['signal_type', 'trend_direction'], name='ml_trend_tr_signal__494d24_idx')],
            },
        ),
    ]
