# Generated by Django 5.2 on 2026-03-27 10:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0006_technicalindicators_precomputed_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('feature_type', models.CharField(choices=[('price', 'Price-based Features'), ('technical', 'Technical Indicators'), ('volatility', 'Volatility Features'), ('volume', 'Volume Features'), ('momentum', 'Momentum Features'), ('pattern', 'Pattern Recognition'), ('fundamental', 'Fundamental Features'), ('custom', 'Custom Features')], max_length=20)),
                ('features_json', models.JSONField(default=dict, help_text='Dictionary of feature names and their configurations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabeledDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('label_type', models.CharField(choices=[('binary', 'Binary Classification (Up/Down)'), ('multi_class', 'Multi-class Classification'), ('regression', 'Regression'), ('risk_reward', 'Risk-Reward Ratio')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Labeling configuration (lookahead periods, thresholds, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MLDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('data', models.JSONField(default=dict, help_text='Structured data with features and labels')),
                ('frequency', models.CharField(choices=[('1min', '1 Minute'), ('5min', '5 Minutes'), ('15min', '15 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_samples', models.IntegerField(default=0)),
                ('feature_names', models.JSONField(default=list, help_text='List of feature names')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='ml_framework.featureset')),
                ('labeled_dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='ml_framework.labeleddataset')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_datasets', to='markets.symbol')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('time_series', 'Time Series')], max_length=20)),
                ('algorithm', models.CharField(choices=[('xgboost', 'XGBoost'), ('lightgbm', 'LightGBM'), ('catboost', 'CatBoost'), ('random_forest', 'Random Forest'), ('gradient_boosting', 'Gradient Boosting'), ('logistic_regression', 'Logistic Regression'), ('neural_network', 'Neural Network'), ('lstm', 'LSTM')], max_length=30)),
                ('hyperparameters', models.JSONField(default=dict, help_text='Model hyperparameters')),
                ('training_date', models.DateField(auto_now_add=True)),
                ('training_samples', models.IntegerField()),
                ('validation_samples', models.IntegerField()),
                ('test_samples', models.IntegerField()),
                ('performance_metrics', models.JSONField(default=dict, help_text='Accuracy, precision, recall, etc.')),
                ('feature_importance', models.JSONField(default=dict, help_text='Feature importance scores')),
                ('model_file_path', models.CharField(blank=True, help_text='Path to saved model file', max_length=500)),
                ('version', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ml_framework.mldataset')),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='ml_framework.featureset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.FloatField(default=100000)),
                ('position_size', models.FloatField(default=0.1, help_text='Position size as % of capital')),
                ('stop_loss', models.FloatField(blank=True, help_text='Stop loss percentage', null=True)),
                ('take_profit', models.FloatField(blank=True, help_text='Take profit percentage', null=True)),
                ('total_return', models.FloatField()),
                ('annualized_return', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('max_drawdown', models.FloatField()),
                ('win_rate', models.FloatField()),
                ('profit_factor', models.FloatField()),
                ('total_trades', models.IntegerField()),
                ('winning_trades', models.IntegerField()),
                ('losing_trades', models.IntegerField()),
                ('trades', models.JSONField(default=list, help_text='List of all trades')),
                ('equity_curve', models.JSONField(default=list, help_text='Equity curve over time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='ml_framework.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('1min', '1 Minute'), ('5min', '5 Minutes'), ('15min', '15 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('prediction_type', models.CharField(choices=[('signal', 'Trading Signal'), ('probability', 'Probability'), ('price_target', 'Price Target')], max_length=20)),
                ('prediction_value', models.FloatField()),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('actual_outcome', models.FloatField(blank=True, null=True)),
                ('was_correct', models.BooleanField(blank=True, null=True)),
                ('features_used', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_framework.mlmodel')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='markets.symbol')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='mldataset',
            index=models.Index(fields=['symbol', 'frequency'], name='ml_framewor_symbol__4ba5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='mldataset',
            index=models.Index(fields=['start_date', 'end_date'], name='ml_framewor_start_d_54b81b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mldataset',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='mlmodel',
            unique_together={('name', 'version')},
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['model', 'symbol', '-timestamp'], name='ml_framewor_model_i_11712b_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['timestamp'], name='ml_framewor_timesta_8f4342_idx'),
        ),
    ]
