from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from markets.models import Symbol, OHLCVData
import json

class TrendConfig(models.Model):
    """
    Configuration for trend following strategy
    """
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)

    # Trend identification
    fast_sma = models.IntegerField(default=100, help_text="Fast SMA for trend identification")
    slow_sma = models.IntegerField(default=200, help_text="Slow SMA for trend identification")

    # Pullback zones
    pullback_ema_fast = models.IntegerField(default=50, help_text="Fast EMA for pullback zone")
    pullback_ema_slow = models.IntegerField(default=100, help_text="Slow EMA for pullback zone")

    # Stochastic settings
    stochastic_period = models.IntegerField(default=14)
    stochastic_overbought = models.IntegerField(default=75)
    stochastic_oversold = models.IntegerField(default=25)

    # VWAP settings
    vwap_anchor = models.CharField(max_length=20, default='session',
                                   choices=[('session', 'Session'), ('week', 'Week'), ('month', 'Month')])

    # Linear regression settings
    regression_period = models.IntegerField(default=20)
    regression_threshold = models.FloatField(default=0.001)

    # Risk management
    risk_reward_ratios = models.JSONField(default=list, help_text="List of risk:reward ratios to test")
    default_stop_loss = models.FloatField(default=0.02, help_text="Default stop loss percentage")

    # Feature toggles
    use_ema_pullback = models.BooleanField(default=True)
    use_stochastic = models.BooleanField(default=True)
    use_vwap_deviation = models.BooleanField(default=True)
    use_regression_trend = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} - {self.fast_sma}/{self.slow_sma} SMA"


class TrendSignal(models.Model):
    """
    Stores trend signals generated by the strategy
    """
    SIGNAL_TYPES = [
        ('LONG', 'Long Entry'),
        ('SHORT', 'Short Entry'),
        ('EXIT', 'Exit'),
    ]

    TREND_DIRECTIONS = [
        ('UPTREND', 'Uptrend'),
        ('DOWNTREND', 'Downtrend'),
        ('SIDEWAYS', 'Sideways'),
    ]

    symbol = models.ForeignKey(Symbol, on_delete=models.CASCADE, related_name='trend_signals')
    config = models.ForeignKey(TrendConfig, on_delete=models.PROTECT, related_name='signals')

    timestamp = models.DateTimeField(db_index=True)
    signal_type = models.CharField(max_length=10, choices=SIGNAL_TYPES)
    trend_direction = models.CharField(max_length=10, choices=TREND_DIRECTIONS)

    # Entry details
    entry_price = models.FloatField()
    entry_confidence = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(1)])

    # Exit details (if applicable)
    exit_price = models.FloatField(null=True, blank=True)
    exit_reason = models.CharField(max_length=50, blank=True)

    # Performance
    actual_return = models.FloatField(null=True, blank=True)
    achieved_rr_ratio = models.FloatField(null=True, blank=True)

    # Technical indicators at entry
    indicators_at_entry = models.JSONField(default=dict)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['symbol', 'timestamp']),
            models.Index(fields=['signal_type', 'trend_direction']),
        ]

    def __str__(self):
        return f"{self.symbol.ticker} - {self.signal_type} @ {self.entry_price} ({self.timestamp})"


class MLTrendDataset(models.Model):
    """
    ML dataset for trend following predictions
    """
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    config = models.ForeignKey(TrendConfig, on_delete=models.PROTECT, related_name='datasets')

    # Data storage
    data = models.JSONField(default=dict, help_text="Features and labels")

    # Metadata
    symbol = models.ForeignKey(Symbol, on_delete=models.CASCADE, related_name='ml_trend_datasets', null=True, blank=True)
    frequency = models.CharField(max_length=10, choices=OHLCVData.FREQUENCY_CHOICES)
    start_date = models.DateField()
    end_date = models.DateField()
    total_samples = models.IntegerField(default=0)
    feature_names = models.JSONField(default=list)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.name} ({self.symbol.ticker if self.symbol else 'All'})"


class MLTrendModel(models.Model):
    """
    Trained ML model for trend following predictions
    """
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    dataset = models.ForeignKey(MLTrendDataset, on_delete=models.PROTECT, related_name='models')
    config = models.ForeignKey(TrendConfig, on_delete=models.PROTECT, related_name='models')

    # Model configuration
    algorithm = models.CharField(max_length=50, choices=[
        ('xgboost', 'XGBoost'),
        ('lightgbm', 'LightGBM'),
        ('random_forest', 'Random Forest'),
    ])
    hyperparameters = models.JSONField(default=dict)

    # Target configuration
    target_rr_ratio = models.FloatField(help_text="Risk:Reward ratio used for labeling")
    target_lookahead = models.IntegerField(help_text="Lookahead periods for take profit")

    # Training metadata
    training_date = models.DateField(auto_now_add=True)
    training_samples = models.IntegerField()

    # Performance metrics
    performance_metrics = models.JSONField(default=dict)
    feature_importance = models.JSONField(default=dict)

    # Model file
    model_file_path = models.CharField(max_length=500, blank=True)
    scaler_file_path = models.CharField(max_length=500, blank=True)

    is_active = models.BooleanField(default=True)
    version = models.CharField(max_length=20, default='1.0.0')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        unique_together = ['name', 'version']

    def __str__(self):
        return f"{self.name} v{self.version} - RR {self.target_rr_ratio}"
